os: linux
dist: xenial
language: minimal
services:
  - docker

before_install:
  - sudo apt-get install screen unzip

script:
  - docker build -t minecraft .
  - mkdir $HOME/bedrock
  - ./minecraft create
  - ./minecraft start
  - ./minecraft say Test Message
  - ./minecraft stop
  - grep 'Server started' $HOME/bedrock/server/Dedicated_Server.txt
  - ./minecraft backup
  - echo "Broken everything" > $HOME/bedrock/server/server.properties
  - echo "Blank" > $HOME/bedrock/server/Dedicated_Server.txt
  - ./minecraft restore `ls -1 $HOME/bedrock/backups/ | tail -1`
  - ./minecraft start
  - ./minecraft stop
  - grep 'Server started' $HOME/bedrock/server/Dedicated_Server.txt

